eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    #可以直接不要自己注册自己，Instances currently registered with Eureka中的Application为No instances available
    register-with-eureka: false

#  eureka的自我保护，关闭
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka     #将Instances currently registered with Eureka中Application的名字改为eureka

server:
  port: 8761

